languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "http://tolehico.github.io/hugo-wercker-example"
canonifyurls = true
title = "mobile-videoplayer.js"
author = "tolehico"

[indexes]
    category = "categories"
    tag = "tags"
[Params]
    AuthorName = "tolehico"
    github = "tolehico/hugo-wercker-example"
    bitbucket = "tolehico"
    twitter = "tolehico"
    email = "tolehico@gmail.com"
    description = "Web video player for mobile browser, especially for ios safari which is disabled to autoplay mp4"
    muut = "mobilevideoplayerjs"
    logo = "https://golang.org/doc/gopher/run.png"
    gaid = "UA-999"
